//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.16 at 04:47:13 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "www.diranieh.com/basic", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.xml;
